version: '3.8'

networks:
    web:
        external: true

services:
    bot:
        build: .
        container_name: kazguide
        command: python -m bot
        restart: always
        env_file:
            - .env
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - web
